# Generated by Django 2.2 on 2022-03-16 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('job_name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('ex', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('salary', models.CharField(max_length=20)),
                ('ex', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('job_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
    ]
