# Generated by Django 2.2 on 2022-03-22 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='link',
            field=models.CharField(max_length=200),
        ),
    ]
