# Generated by Django 2.2 on 2022-03-24 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20220323_0112'),
    ]

    operations = [
        migrations.DeleteModel(
            name='student',
        ),
    ]
